### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by michaelliu1210**
plz

### CODE REVIEW

**Comment by HenryPersonalWeb** [comment]
?你想干什么

**Comment by HenryPersonalWeb** [comment]
快说

**Comment by michaelliu1210** [comment]
> ?你想干什么

are you henryL

**Comment by michaelliu1210** [comment]
> 快说

Im joining your site

**Comment by michaelliu1210** [comment]
> > 快说
> 
> Im joining your site

update readme file in the main site to a hyperlink of my site

**Comment by michaelliu1210** [comment]
> > > 快说
> > 
> > 
> > Im joining your site
> 
> update readme file in the main site to a hyperlink of my site

please accept request and allow merge plz 😀

**Comment by HenryPersonalWeb** [comment]
? OK



在 2022-07-11 21:17:19，"michaelliu1210" ***@***.***> 写道：

快说

Im joining your site

update readme file in the main site to a hyperlink of my site

please accept request and allow merge plz 😀

**Comment by michaelliu1210** [comment]
why you closed da pull request!

**Comment by michaelliu1210** [comment]
> ? OK 在 2022-07-11 21:17:19，"michaelliu1210" ***@***.***> 写道： 快说 Im joining your site update readme file in the main site to a hyperlink of my site please accept request and allow merge plz 😀 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

OK
now im gonna do work on both max & your site 😊

**Pull request closed without merging**
